- package.json
- src/CodeParser/CParser.ts
- src/Config.ts
- src/DocGen/CGen.ts
This prevents that compiler keywords will be interpreted as return type.
This change should also introduce the possibility to disable filling in the return type into the @return keyword for doxygen.
> Remove compiler keywords from the method/function signature

- src/CodeParser/CParser/CParser.ts
- src/CodeParser/CodeParserController.ts
-- Fixed bug where using a different trigger sequence then "*" causes a newline to be addd between the comment and the documented entity.
Example when using `///` as a trigger the following comment used to be generated:
```
/**
* \brief 
* 
* \param matrix_data 
*/
matrix(std::initializer_list<std::initializer_list<T>> matrix_data)
```
-- Fixed bug where using unsigned or signed modifiers would result in bad comments. Resolves issue: https://github.com/christophschlosser/doxdocgen/issues/31
> Fixed parser bug and comment generation bug.

- package.json
This fixes #40. 
It was necessary to listen for C changes as well as C++ changes in order to get the events. If the file was changed to C++ and back to C it still worked because then the event has been fired.
No unit tests necessary.
> Activate extension for C

- package.json
- src/Config.ts
- src/Lang/Cpp/CppParser.ts
- src/test/CppTests/Config.test.ts
Fix #52. Allows to customize the number of lines to get for method signature detection.
> Customize the number of lines to get

- src/CodeParserController.ts
Fix #67 
Use regex to match comment trigger sequence instead of a simple trim() and check if current line is in a comment block so no other comment like in #67 is generated.
> Don’t trigger if there’s whitespace after sequence

- src/Lang/Cpp/CppParser.ts
- src/test/CppTests/Parameters.test.ts
Fixes #91.
Improve regex to not mistakenly detect variables starting with parts of reserved keywords.
> Fix type as variable name

- .gitignore
- src/Lang/Cpp/CppParser.ts
- src/test/CppTests/Parameters.test.ts
This fixes #102.
Enums were not treated as type specifier. This led to the enum name being detected as parameter name.
> Enums now are treated as type correctly

- src/Lang/Cpp/CppParser.ts
- src/test/CppTests/FunctionPointer.test.ts
Fix #123.
Add a new method to check if there is an array pointer in the current line.
> Add arraypointers to detection

- src/Lang/Cpp/CppParser.ts
- src/test/CppTests/Attributes.test.ts
Fix #136 
If the terminating character is the first one on the next line
it can cause the buffer to fill and thus produce malformed
text to parse.
> End of declaration problem fixed

- src/Lang/Cpp/CppDocGen.ts
- src/test/CppTests/Config.test.ts
Fix #127.
Treat template string containing `\n` as multiple lines.
> Add support for multiline template

- package.json
- src/CodeParserController.ts
Enable CUDA language support
The CUDA language [is registered](https://reviews.llvm.org/D70041) by the [`vscode-clangd`](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) and [`vscode-cudacpp`](https://marketplace.visualstudio.com/items?itemName=kriegalex.vscode-cudacpp) plugins.
[A similar PR](https://github.com/microsoft/vscode-cpptools/pull/4585) to this one has been integrated into the Microsoft [`vscode-cpptools`](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) extension to enable debugging.
> Enable CUDA language support

- package-lock.json
- src/Lang/Cpp/CppParser.ts
- src/test/CppTests/Preprocessor.test.ts
Fixes #142.
The preprocessor wasn't ignored and in case something else that was "detectable" by the add-on was found in lines further down the generation was triggered and mistakenly replaced the first few characters of the macro thinking it was another comment.
> Return once we found preprocessor stuff

- README.md
- package.json
- src/Config.ts
- src/Lang/Cpp/CppParser.ts
- src/test/CppTests/Config.test.ts
Implements #152.
It's now possible to filter arbitrary keywords from processing before any of the heuristics to detect parameters, return type and so on are applied.
> Add option to filter keywords

- src/Lang/Cpp/CppParser.ts
- src/test/CppTests/FileDescription.test.ts
Fix #161 again.
Return an empty line (which the heuristic later on checks) if preprocessor magic is found unless it's a macro.
> Fix #161 again

- CHANGELOG.md
- package.json
- src/Lang/Cpp/CppParser.ts
- src/test/CppTests/Templates.test.ts
Fixes #170 
The `tparam` check is checking for whitespaces. Many code styles surround `=` with whitespaces and here the detection fails.
> Fix default value in tparams

- CHANGELOG.md
- README.md
- package.json
- src/Config.ts
- src/Lang/Cpp/CppDocGen.ts
- src/test/CppTests/Config.test.ts
Implements #169 
You can now specify customs tags that will be added to each comment.
> Add custom tags to generic order

- CHANGELOG.md
- LICENSE
- package-lock.json
- package.json
- src/Lang/Cpp/CppDocGen.ts
- src/test/CppTests/Config.test.ts
Fixes #110 
Add possibility to get the content of env vars in templated strings.
If not env var can be found the name of the env var will be inserted.
> Add env-var to replace env var in template strings

- src/test/CppTests/Attributes.test.ts
- src/test/CppTests/Con-AndDestructor.test.ts
- src/test/CppTests/Config.test.ts
- src/test/CppTests/FileDescription.test.ts
- src/test/CppTests/FunctionPointer.test.ts
- src/test/CppTests/Operators.test.ts
- src/test/CppTests/Parameters.test.ts
- src/test/CppTests/Preprocessor.test.ts
- src/test/CppTests/ReturnTypes.test.ts
- src/test/CppTests/SmartText.test.ts
- src/test/CppTests/Templates.test.ts
- src/test/CppTests/TrailingReturns.test.ts
Due to message: deprecated since v9.9.0 - use strictEqual() instead.
Due to message: deprecated since v9.9.0 - use strictEqual() instead.
> Replaced assert.equal() calls by assert.strictEqual() calls

- package.json
1. Make the setting descriptions to proper `markdownDescription` as necessary.
2. As you can see in the gif, I was confused by what values are valid, because I click on the setting and then the default array is empty. (I think it's an issue of vscode itself). So I added those valid values in the descriptions.
> Nicer setting descriptions

- src/Lang/Cpp/CppDocGen.ts
- src/test/CppTests/Config.test.ts
This closes #204 
~~Copied file-scoped tag branches -> generic tag branches, so it can be properly expanded.~~
The common tags that can be used in both `File` comments and `Method` comments are handled by one same function. So it can be both expanded properly.
> Fix tags in generic order not expanded

- src/DoxygenCompletionItemProvider.ts
- src/Lang/Cpp/CppDocGen.ts
- src/templatedString.ts
- src/test/CppTests/Config.test.ts
Closes #206 
Also the `@code` command needs `{.cpp}` instead of `.cpp` as the language id block, see [here](https://www.doxygen.nl/manual/commands.html#cmdcode), my bad!
> fix indent not expanded in file comments

- src/GitConfig.ts
Or is it a fix...
Allows a per-workspace git user and email address.
Note that this change doesn't cope with multiple workspaces in a single vscode instance. It would probably have to defer the config lookup and use the appropriate workspace root for the file being edited at that point.
Thanks for the extension, hope this is useful and it should at least be good for most cases!
Regards
> Use vscode.workspace.workspaceFolders[0] to construct SimpleGit instance.

- package.json
- src/CodeParserController.ts
- Issue: doxdocgen is not triggered for CUDA files because the current [language identifier](https://code.visualstudio.com/docs/languages/identifiers) in the `activationEvents` triggers is `cuda` but this is not correct because on the [VS Code website](https://code.visualstudio.com/docs/languages/identifiers) it lists `cuda-cpp` for CUDA &mdash;this issue was mainly noticed because doxdocgen was not working in CUDA files (.cu, .cuh).
- Fix: CUDA support is added again by correcting the language identifier to the &mdash;at this time&mdash; correct value.
> Change Language identifier for CUDA to correct one

- README.md
Use the `jsonc` instead of the `json` syntax highlighter in the README
to avoid the comments being marked as error.
The GitHub syntax highlighter seems to have parsing issues with the use
of comment tokens `/**` and `*/` within strings: it thinks those are
JSON comments, even though they are normal strings. Converting the JSON
fragment into a full JSON document with curly braces at the beginning
and end brings the parser back on track and gets us the right syntax
highlighting.
> README: Use syntax highlighter that allows comments
