.travis.yml

Build on all branches except those beginning with `release-*`

Improve travis build trigger

---

README.md

Remove C and add C++11 and newer

Update README to match currently supported langs

---

README.md
src/CodeParser/CParser.ts
src/DocGen/CGen.ts

Fixes #10 
(At least partially)

Fix param generation for function pointers

---

src/Lang/Cpp/CppParser.ts

Add the missing operator to introduce a fully working state

Missing tests

---

CHANGELOG.md
README.md
package.json

Release 0.1.0

---

.gitignore
.travis.yml
README.md
coverconfig.json
package.json
publish_coverage.sh
src/test/index.ts

Add coverage to test stages to further improve quality.

Add coverage

---

package.json

Add Moment as runtime dependency

---

.travis.yml
README.md
appveyor.yml

Add gitter

---

package.json
src/extension.ts

Add notification for 0.3.0 that the config changed

Add config changed notification

---

package.json
src/Config.ts
src/Lang/Cpp/CppDocGen.ts

Update brief template to better play with smart text

Update brief template for smart text

---

.vscodeignore
CHANGELOG.md
LICENSE
README.md
package.json
src/extension.ts

Release 0.3.0

---

CHANGELOG.md
package.json
src/extension.ts

Release 0.3.1

---

.gitignore
src/CodeParserController.ts

Fixes #79 .
Extend validity check if clause to catch undefined and not just null.

Check if editor and event are undefined 

---

CHANGELOG.md
package.json
src/extension.ts

Release 0.3.2 with bug fix for #79

Release 0.3.2

---

CHANGELOG.md
package.json
src/extension.ts

Release 0.3.3

---

CHANGELOG.md
package.json
src/extension.ts

Release 0.4.1

---

CHANGELOG.md
package.json
src/extension.ts

Release 0.4.2

---

package.json
src/extension.ts

Release 0.5.0

---

package-lock.json
package.json
src/Lang/Cpp/CppParser.ts
src/test/CppTests/Con-AndDestructor.test.ts
src/test/CppTests/Operators.test.ts

This should fix #119.
The autocomplete of VS Code comments made things quite hard and this fixes an overlooked case.
No tests possible with the current setup of tests.

Fix vscodeautocomplete detection

---

package-lock.json
package.json

Attempt to fix security vulnerabilities

Attempt to fix dependencies

---

src/Lang/Cpp/CppParser.ts
src/test/CppTests/Parameters.test.ts

Fix #121.
Add `restrict` to list of typeKeywords so it will be stripped.

Ignore restrict keyword

---

CHANGELOG.md
package.json
src/extension.ts

Release 0.5.2 containing the fixed bug #136

Release 0.5.2

---

.travis.yml
CHANGELOG.md
package.json
src/extension.ts

Release 0.6.0

---

CHANGELOG.md
package-lock.json
package.json
src/extension.ts

Prepare release 0.7.0

---

CHANGELOG.md
package-lock.json
package.json
src/extension.ts

Release 0.7.1

---

CHANGELOG.md
package-lock.json
package.json
src/extension.ts

Release 0.7.2

---

CHANGELOG.md
package-lock.json
package.json
src/extension.ts

Release 0.8.0

---

CHANGELOG.md
LICENSE
package-lock.json
package.json
src/Lang/Cpp/CppDocGen.ts
src/extension.ts
src/test/CppTests/Config.test.ts

Revert #175 because there seem to be problems with packaging the node_modules.

Release 0.8.1

---

.travis.yml
CHANGELOG.md
package-lock.json
package.json
src/extension.ts

Release 0.8.2 with vice 1.31.0

Use different vsce version for release 0.8.2

---

.travis.yml
CHANGELOG.md
package-lock.json
package.json
src/Lang/Cpp/CppDocGen.ts
src/extension.ts
src/test/CppTests/Config.test.ts

Release 1.0.0 with fix #177 and reenabling #175

Release 1.0.0

---

src/Lang/Cpp/CppParser.ts
src/test/CppTests/FileDescription.test.ts
src/test/CppTests/TestSetup.ts

Due to https://github.com/cschlosser/doxdocgen/issues/141
https://github.com/cschlosser/doxdocgen/issues/141
Triggers the autocomplete for file description for files without includes.

Added file description in first line

---

CHANGELOG.md
package-lock.json
package.json
src/extension.ts

Prepare release 1.0.1 which closes #141

Release 1.0.1

---

CHANGELOG.md
package-lock.json
package.json
src/extension.ts
src/test/CppTests/Config.test.ts
src/test/CppTests/TrailingReturns.test.ts

Release 1.1.0

---

CHANGELOG.md
package.json
src/extension.ts
yarn.lock

Prepare relase 1.2.1 with changes from #214

Prepare relase 1.2.1

---

CHANGELOG.md
package.json
src/extension.ts

Prepare release 1.3.0

---

CHANGELOG.md
package.json
src/extension.ts

PR for release 1.3.1
Contains #224 and #229

Prepare release 1.3.1

---

CHANGELOG.md
package.json
src/extension.ts

Prepare release 1.3.2

---

CHANGELOG.md
package.json
src/extension.ts

Prepare release 1.4.0

---

README.md
package.json

Fix typo in README.md
